name: update-blocklists

on:
  schedule:
    - cron: '0 * * * *'  # Every hour
  workflow_dispatch:       # Allow manual runs

jobs:
  update-blocklist:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch, filter, and write blocklist
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
        run: |
          mkdir -p docs/blocklists
          curl -fsSL --max-time 60 "https://raw.githubusercontent.com/hagezi/dns-blocklists/refs/heads/main/domains/light.txt" > docs/blocklists/light.txt
          curl -fsSL --max-time 60 "https://raw.githubusercontent.com/hagezi/dns-blocklists/refs/heads/main/domains/multi.txt" > docs/blocklists/multi.txt
          curl -fsSL --max-time 60 "https://raw.githubusercontent.com/hagezi/dns-blocklists/refs/heads/main/domains/pro.txt" > docs/blocklists/pro.txt
          curl -fsSL --max-time 60 "https://raw.githubusercontent.com/hagezi/dns-blocklists/refs/heads/main/domains/pro.plus.txt" > docs/blocklists/pro.plus.txt
          curl -fsSL --max-time 60 "https://raw.githubusercontent.com/hagezi/dns-blocklists/refs/heads/main/domains/ultimate.txt" > docs/blocklists/ultimate.txt
          curl -fsSL --max-time 60 "https://raw.githubusercontent.com/hagezi/dns-blocklists/refs/heads/main/domains/doh.txt" > docs/blocklists/doh.txt
          curl -fsSL --max-time 60 "https://raw.githubusercontent.com/hagezi/dns-blocklists/refs/heads/main/domains/tif.txt" > docs/blocklists/tif.txt
          curl -fsSL --max-time 60 "https://raw.githubusercontent.com/hagezi/dns-blocklists/refs/heads/main/domains/blocklist-referral.txt" > docs/blocklists/blocklist-referral.txt
          curl -fsSL -H "Authorization: Bearer $CF_API_TOKEN" "https://api.cloudflare.com/client/v4/radar/datasets/ranking_top_1000000" > top.txt
          comm -12 \
            <(grep -v '^[#$]' docs/blocklists/light.txt | tr '[:upper:]' '[:lower:]' | sort) \
            <(tail -n +2 top.txt | cut -d',' -f2 | tr '[:upper:]' '[:lower:]' | sort) \
            > docs/blocklists/basic.txt

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/blocklists
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "chore: update filtered blocklist [skip ci]"
            git push origin master
          fi
